### PR TITLE
updated the readme file

### PR DESCRIPTION
**Pull request by tGodson**

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @tGodson :wave:
-
You have done a splendid job! :tada: I love how clean and modular your code is. Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## Friendly reminder: You should make sure that your repo looks professional before review.
-  I also noticed that the project is complete and everything is working well as it should but there are no ways to track your progress as there are no meaningful commits in your repo for that matter.
- Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
- Your project also needs to have stickler linter activated to validate your stylesheets.
- Don't forget to update your README as well.
##
This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!
-
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @christianotieno, you did a great job 👍 However, we forgot to enable stickler for our project as pointed by the previous TSE 🙂 
- Also let us increase the width of the main page so it looks like the original
- Let us edit our PR so it has a title and a short summary to describe our project

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Comment by tGodson** [comment]
**Apple Website Clone request**
This is a clone of the old version of Apple website's web page. Built with HTML, CSS and BOOTSTRAP.

**Comment by adaorachi** [comment]
👋 Hi @tGodson,

Good Job on the work done so far on this project. Your project looks very nice. 💯💥
You've done well on implementing the changes required, however, there are a couple of issues you left unfixed and some arising ones. You'll need to get them fixed before you can get approval 👍 for this project.

---
### **CHANGES REQUIRED** ♻️ 
---

- [x] Ensure to edit your Pull Request to have a title and summary to describe your project as suggested in the previous review.

---

- [x] You have a broken image link in your README file. Kindly fix that.

---

- [x] Your project site has a white space trailing the entire width. This can be noticed with the scroll bar highlighted in the screenshot below. Search for the element(s) causing the overflow and fix it using appropriate CSS selectors.

Annotation 2020-04-12 150324

---
After implementing the changes requested above, you can request for another review by submitting a code review form.
---

Should you have any questions or need any help, please do reach out to me on Slack with the username (@adaorachi).

Good Luck in it and Happy Coding! ☺️ 

**MaryAnn Chukwuka**

**Comment by tGodson** [comment]
**Apple Webpage Clone**
This is a clone of Apple's webpage built with HTML5, CSS3 and bootstrap. In the body of the clone is the main part which contains the navigation bar, a background picture, the main heading and a paragraph. Below the main section is a banner of 4 pictures then the footer.

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :+1: :100: 

Hi @tGodson :smile: :smile: 

Congrats for the hard work :muscle: Your project was approved :fireworks: :fireworks:

:bug: The screenshot is not showing up on the readme file. Can you please fix it before merging this branch into master? - there is no need to submit it for another code review!

:1st_place_medal: I loved the favicon you added on your page :trophy: 

_SUGGESTION FOR THE NEXT PROJECTS:_

:bulb: Just to clarify: On the first pull request, it is required to add a short summary that describes what you guys on the project. For the other subsequent pull requests,  what you have to summarize is what you fixed after the review and before the submissions for another review. :+1: :100: 

:bulb: You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''apple-page'' instead of ''feature', for example. It will be more descriptive :smile_cat: 


If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)

### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
